import 'package:auto_route/auto_route.dart';
import 'package:wallet_app/ui/pages/add_balance/add_balance.dart';
import 'package:wallet_app/ui/pages/add_balance/payment_page/esewa/esewa_topup_page.dart';
import 'package:wallet_app/ui/pages/add_balance/payment_page/stripe/stripe_card_selection_page.dart';
import 'package:wallet_app/ui/pages/add_balance/payment_page/stripe/stripe_new_card_payment_page.dart';
import 'package:wallet_app/ui/pages/add_balance/payment_page/stripe/stripe_save_card_payment_page.dart';
import 'package:wallet_app/ui/pages/alerts/alert_settings/alert_prefecture_chooser.dart';
import 'package:wallet_app/ui/pages/alerts/alerts_page.dart';
import 'package:wallet_app/ui/pages/alerts/alerts_tab_page.dart';
import 'package:wallet_app/ui/pages/alerts/detail/alert_detail_page.dart';
import 'package:wallet_app/ui/pages/auth/forgot_password_screen.dart';
import 'package:wallet_app/ui/pages/auth/login_screen.dart';
import 'package:wallet_app/ui/pages/auth/register_screen.dart';
import 'package:wallet_app/ui/pages/auth/validate_user_screen.dart';
import 'package:wallet_app/ui/pages/banner_detail_page/banner_detail_page.dart';
import 'package:wallet_app/ui/pages/coupons/coupon_page.dart';
import 'package:wallet_app/ui/pages/notification/notification_detail_page.dart';
import 'package:wallet_app/ui/pages/settings/device_management/user_devices_page.dart';
import 'package:wallet_app/ui/pages/reward_point/reward_point_home.dart';
import 'package:wallet_app/ui/pages/search/search_home.dart';
import 'package:wallet_app/ui/pages/settings/about_us/about_us.dart';
import 'package:wallet_app/ui/pages/settings/change_password/change_password_page.dart';
import 'package:wallet_app/ui/pages/settings/contact_us.dart/contact_us_page.dart';
import 'package:wallet_app/ui/pages/settings/security/security_page.dart';
import 'package:wallet_app/ui/pages/settings/security/set_mpin_page.dart';
import 'package:wallet_app/ui/pages/settings/security/verify_number.dart';
import 'package:wallet_app/ui/pages/settings/settings_page.dart';
import 'package:wallet_app/ui/pages/utility_payment/detail_pages/electricity/nea_page.dart';
import 'package:wallet_app/ui/pages/utility_payment/detail_pages/internet/payment/isp_payment_page.dart';
import 'package:wallet_app/ui/pages/utility_payment/detail_pages/khanepani/khanepani_page.dart';
import 'package:wallet_app/ui/pages/utility_payment/detail_pages/topup/topup_page.dart';
import 'package:wallet_app/ui/pages/japanese_manner/japanese_manner_detail.dart';
import 'package:wallet_app/ui/pages/japanese_manner/japanese_manner_page.dart';
import 'package:wallet_app/ui/pages/news/detail_page/news_detail.dart';
import 'package:wallet_app/ui/pages/notification/notification_list.dart';
import 'package:wallet_app/ui/pages/partner_services/buy_package.dart';
import 'package:wallet_app/ui/pages/partner_services/partner_service_payment/partner_service_payment.dart';
import 'package:wallet_app/ui/pages/partner_services/partner_services.dart';
import 'package:wallet_app/ui/pages/partner_services/service_detail.dart';
import 'package:wallet_app/ui/pages/pdf_viewer/pdf_viewer.dart';
import 'package:wallet_app/ui/pages/profile_page/profile_page.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/about/edit_basic_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/academics/edit_academic_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/address/current_address/edit_current_address_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/address/contact_address/edit_contact_address_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/other/edit_other_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/qualification/edit_qualification_info.dart';
import 'package:wallet_app/ui/pages/resume/resume_tab_pages/work/edit_work_info.dart';
import 'package:wallet_app/ui/pages/splash/splash_screen.dart';
import 'package:wallet_app/ui/pages/tab_bar/tab_bar_screen.dart';
import 'package:wallet_app/ui/pages/transactions/transaction_detail_page.dart';
import 'package:wallet_app/ui/pages/transactions/transactions_page.dart';
import 'package:wallet_app/ui/pages/utility_payment/detail_pages/tv/payment/tv_payment_page.dart';
import 'package:wallet_app/ui/pages/webview/app_web_view.dart';
import 'routes.gr.dart';

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends $AppRouter {
  @override
  final List<AutoRoute> routes = [
    AutoRoute(page: SplashRoute.page, initial: true),
    AutoRoute(page: LoginRoute.page),
    AutoRoute(page: ForgotPasswordRoute.page),
    AutoRoute(page: VerifyUserRoute.page),
    AutoRoute(page: SignupRoute.page),
    AutoRoute(page: TabBarRoute.page),
    AutoRoute(page: EditBasicInfoFormRoute.page),
    AutoRoute(page: EditCurrentAddressInfoFormRoute.page),
    AutoRoute(page: EditContactAddressInfoFormRoute.page),
    AutoRoute(page: EditWorkInfoFormRoute.page),
    AutoRoute(page: EditAcademicInfoFormRoute.page),
    AutoRoute(page: EditQualificationInfoFormRoute.page),
    AutoRoute(page: EditOtherInfoFormRoute.page),
    AutoRoute(page: NewsDetailRoute.page),
    AutoRoute(page: AppWebViewRoute.page),
    AutoRoute(page: ProfileRoute.page),
    AutoRoute(page: PartnerServicesRoute.page),
    AutoRoute(page: ServicesDetailRoute.page),
    AutoRoute(page: JapaneseMannerRoute.page),
    AutoRoute(page: JapaneseMannerDetailRoute.page),
    AutoRoute(page: AlertsRoute.page),
    AutoRoute(page: AlertsTabRoute.page),
    AutoRoute(page: AlertDetailRoute.page),
    AutoRoute(page: AlertDetailFomApiRoute.page),
    AutoRoute(page: AlertPrefectureChooserRoute.page),
    AutoRoute(page: AddBalanceRoute.page),
    AutoRoute(page: StripePaymentCardSelectionRoute.page),
    AutoRoute(page: StripeNewCardPaymentRoute.page),
    AutoRoute(page: StripeSaveCardPaymentRoute.page),
    AutoRoute(page: EsewaTopupRoute.page),
    AutoRoute(page: BannerDetailRoute.page),
    AutoRoute(page: PdfViewerRoute.page),
    AutoRoute(page: TopUpRoute.page),
    AutoRoute(page: PartnerServicePaymentRoute.page),
    AutoRoute(page: TransactionRoute.page),
    AutoRoute(page: TransactionDetailRoute.page),
    AutoRoute(page: TransactionDetailFromAPiRoute.page),
    AutoRoute(page: NotificationListRoute.page),
    AutoRoute(page: BuyPackageRoute.page),
    AutoRoute(page: CouponRoute.page),
    AutoRoute(page: NotificationDetailRoute.page),
    AutoRoute(page: JPMannerDetailFromAPiRoute.page),
    AutoRoute(page: ServiceDetailFromAPIRoute.page),
    AutoRoute(page: SearchRoute.page),
    AutoRoute(page: RewardPointsHomeRoute.page),
    AutoRoute(page: SettingsRoute.page),
    AutoRoute(page: ChangePasswordRoute.page),
    AutoRoute(page: AboutUsRoute.page),
    AutoRoute(page: ContactUsRoute.page),
    AutoRoute(page: UserDevicesListRoute.page),
    AutoRoute(page: NEAPaymentRoute.page),
    AutoRoute(page: KhanepaniPaymentRoute.page),
    AutoRoute(page: SecurityRoute.page),
    AutoRoute(page: SetMpinRoute.page),
    AutoRoute(page: VerifyNumberRoute.page),
    AutoRoute(page: ISPPaymentRoute.page),
    AutoRoute(page: TVPaymentRoute.page),
  ];
}
