include: package:lint/analysis_options.yaml  

analyzer:
  exclude: 
    - "**/*.config.dart"
    - "**/*.freezed.dart"

  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false

  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
  
linter:
  rules:
    sort_pub_dependencies: false
    constant_identifier_names: false