name: wallet_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+15 # Dont forget in update app version in the config.json file after version is changed!



environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  advance_pdf_viewer:
    git:
      url: https://github.com/AdiD253/pdf_viewer.git
      ref: pdf-viewer-file-fix
  assorted_layout_widgets: ^5.0.2     
  another_flushbar: ^1.10.24          
  auto_route: ^2.2.0                
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0-nullsafety.0   
  dartz: ^0.10.0-nullsafety.2   
  esewa_pnp:
    # path: ../sdk/esewa_pnp
    git:
      url: https://github.com/asisadh/esewa_pnp.git
      ref: null-safety
  equatable: ^2.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  fl_chart: ^0.36.1                           
  flutter_bloc: ^7.0.0  
  fluttercontactpicker: ^4.4.0              
  flutter_downloader: ^1.6.1      
  flutter_facebook_auth: ^3.3.3+1              
  flutter_html: ^2.0.0  
  flutter_local_notifications: ^8.0.0              
  flutter_secure_storage: ^4.2.0 
  flutter_svg: ^0.22.0               
  form_validator: ^1.0.0-nullsafety.1   
  freezed_annotation: ^0.14.2               
  get_it: ^7.1.3            
  geolocator: ^7.4.0 
  google_maps_flutter: ^2.0.5                
  google_sign_in: ^5.0.3                
  http: ^0.13.3               
  image_picker: ^0.8.3+1   
  ime_pay: ^0.0.6             
  injectable: ^1.4.0    
  internet_connection_checker: ^0.0.1+2           
  kana_kit: ^2.0.0                              
  multi_select_flutter: ^4.0.0                
  path_provider: ^2.0.1                
  permission_handler: ^8.1.4+2                
  share: ^2.0.1                
  shared_preferences: ^2.0.5                
  sign_in_with_apple: ^3.0.0  
  sliver_tools: ^0.2.5              
  sms_autofill: ^2.0.0                
  sqflite: ^2.0.0+3    
  syncfusion_flutter_charts: ^19.1.66+1          
  url_launcher: ^6.0.3                
  youtube_player_flutter: ^8.0.0
  google_mobile_ads: ^0.13.4
  facebook_audience_network: ^1.0.0-nullsafety.0
  flutter_khalti: ^1.1.0
  flutter_web_browser: ^0.15.0
  webview_flutter: ^2.0.13
  marquee: ^2.2.0
  firebase_analytics: ^8.2.0
  image_cropper: ^1.4.1
  device_info_plus: ^2.1.0
  local_auth: ^1.1.7
  firebase_crashlytics: ^2.2.1
  package_info_plus: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0                
  build_runner: ^2.1.2                
  freezed: ^0.14.2               
  injectable_generator: ^1.4.0                      
  lint: ^1.5.3                
  mockito: ^5.0.7                
  network_image_mock: ^2.0.0    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/navigation_bar/
    - assets/images/top_up/
    - assets/images/home/
    - assets/images/errors/
    - assets/images/home/utility-payment/
    - assets/images/navigation_tabs/
    - assets/images/news/
    - assets/images/auth/
    - assets/images/placeholders/
    - assets/images/resume/
    - assets/images/pop_up/
    - assets/images/coupon/
    - assets/images/more/
    - assets/images/profile/
    - assets/images/alerts/
    - assets/images/remit/
    - assets/images/splash/
    - assets/images/banner_details/
    - assets/images/transaction/
    - assets/images/notification/
    - assets/images/services/
    - config/
    - lib/features/location_information/data/datasource/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
