name: wallet_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.8+25 # Dont forget in update app version in the app_config.json file after version is changed!

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.5"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  flutter_cached_pdfview: ^0.4.2
  assorted_layout_widgets: ^8.0.4     
  another_flushbar: ^1.12.30          
  auto_route: any            
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1   
  dartz: ^0.10.1   
  esewa_pnp: ^2.0.1
    # path: ../sdk/esewa_pnp
    # git:
    #   url: https://github.com/asisadh/esewa_pnp.git
    #   ref: null-safety
  # equatable: ^2.0.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  fl_chart: ^0.62.0                           
  flutter_bloc: ^8.1.3  
  fluttercontactpicker: ^4.7.0              
  flutter_downloader: ^1.10.5      
  flutter_facebook_auth: ^5.0.11         
  flutter_html: ^3.0.0-beta.2  
  flutter_local_notifications: ^15.1.1              
  flutter_secure_storage: ^8.1.0 
  flutter_svg: ^2.0.5               
  form_validator: ^2.1.1   
  freezed_annotation: ^2.4.1               
  get_it: ^7.6.0            
  geolocator: ^10.0.1 
  google_maps_flutter: ^2.3.0                
  google_sign_in: ^6.1.5                
  http: ^0.13.6               
  image_picker: ^1.0.4   
  # ime_pay: ^0.0.6             
  injectable: ^2.1.0    
  internet_connection_checker: ^1.0.0+1           
  kana_kit: ^2.0.0                              
  multi_select_flutter: ^4.1.3                
  path_provider: ^2.1.1                
  permission_handler: ^10.4.5                
  share: ^2.0.4      
  shared_data:
    # path: "../flutter-data-share"
    git:
      url: https://aashishadhikari@bitbucket.org/aashishadhikari/flutter-data-share.git
  shared_preferences: ^2.2.1                
  sign_in_with_apple: ^4.3.0
  sliver_tools: ^0.2.12              
  sms_autofill: ^2.3.0                
  sqflite: ^2.2.8+4    
  syncfusion_flutter_charts: ^21.2.4          
  url_launcher: ^6.1.11                
  youtube_player_flutter: ^8.1.2
  google_mobile_ads: ^3.0.0
  # facebook_audience_network: ^1.0.0-nullsafety.0
  flutter_khalti: any
  flutter_web_browser: ^0.17.1
  webview_flutter: ^4.2.4
  marquee: ^2.2.3
  firebase_analytics: ^10.4.5
  image_cropper: ^4.0.1
  device_info_plus: any
  local_auth: ^2.1.6
  firebase_crashlytics: ^3.3.5
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3                
  freezed: ^2.4.1               
  injectable_generator: ^2.1.6                      
  lint: ^2.0.20                
  mockito: ^5.4.0                
  network_image_mock: ^2.1.1    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/navigation_bar/
    - assets/images/top_up/
    - assets/images/home/
    - assets/images/errors/
    - assets/images/home/utility-payment/
    - assets/images/navigation_tabs/
    - assets/images/news/
    - assets/images/auth/
    - assets/images/placeholders/
    - assets/images/resume/
    - assets/images/pop_up/
    - assets/images/coupon/
    - assets/images/more/
    - assets/images/profile/
    - assets/images/alerts/
    - assets/images/remit/
    - assets/images/splash/
    - assets/images/banner_details/
    - assets/images/transaction/
    - assets/images/notification/
    - assets/images/services/
    - config/
    - lib/features/location_information/data/datasource/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
